from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(990, 592)
        self.H = QtWidgets.QPushButton(parent=Dialog)
        self.H.setGeometry(QtCore.QRect(50, 50, 51, 51))
        self.H.setObjectName("H")
        self.Li = QtWidgets.QPushButton(parent=Dialog)
        self.Li.setGeometry(QtCore.QRect(50, 100, 51, 51))
        self.Li.setObjectName("Li")
        self.Na = QtWidgets.QPushButton(parent=Dialog)
        self.Na.setGeometry(QtCore.QRect(50, 150, 51, 51))
        self.Na.setObjectName("Na")
        self.K = QtWidgets.QPushButton(parent=Dialog)
        self.K.setGeometry(QtCore.QRect(50, 200, 51, 51))
        self.K.setObjectName("K")
        self.Rb = QtWidgets.QPushButton(parent=Dialog)
        self.Rb.setGeometry(QtCore.QRect(50, 250, 51, 51))
        self.Rb.setObjectName("Rb")
        self.Cs = QtWidgets.QPushButton(parent=Dialog)
        self.Cs.setGeometry(QtCore.QRect(50, 300, 51, 51))
        self.Cs.setObjectName("Cs")
        self.Fr = QtWidgets.QPushButton(parent=Dialog)
        self.Fr.setGeometry(QtCore.QRect(50, 350, 51, 51))
        self.Fr.setObjectName("Fr")
        self.Mg = QtWidgets.QPushButton(parent=Dialog)
        self.Mg.setGeometry(QtCore.QRect(100, 150, 51, 51))
        self.Mg.setObjectName("Mg")
        self.Sr = QtWidgets.QPushButton(parent=Dialog)
        self.Sr.setGeometry(QtCore.QRect(100, 250, 51, 51))
        self.Sr.setObjectName("Sr")
        self.Ra = QtWidgets.QPushButton(parent=Dialog)
        self.Ra.setGeometry(QtCore.QRect(100, 350, 51, 51))
        self.Ra.setObjectName("Ra")
        self.Ba = QtWidgets.QPushButton(parent=Dialog)
        self.Ba.setGeometry(QtCore.QRect(100, 300, 51, 51))
        self.Ba.setObjectName("Ba")
        self.Ca = QtWidgets.QPushButton(parent=Dialog)
        self.Ca.setGeometry(QtCore.QRect(100, 200, 51, 51))
        self.Ca.setObjectName("Ca")
        self.Be = QtWidgets.QPushButton(parent=Dialog)
        self.Be.setGeometry(QtCore.QRect(100, 100, 51, 51))
        self.Be.setObjectName("Be")
        self.Sc = QtWidgets.QPushButton(parent=Dialog)
        self.Sc.setGeometry(QtCore.QRect(150, 200, 51, 51))
        self.Sc.setObjectName("Sc")
        self.H_18 = QtWidgets.QPushButton(parent=Dialog)
        self.H_18.setGeometry(QtCore.QRect(150, 300, 51, 51))
        self.H_18.setText("")
        self.H_18.setObjectName("H_18")
        self.Y = QtWidgets.QPushButton(parent=Dialog)
        self.Y.setGeometry(QtCore.QRect(150, 250, 51, 51))
        self.Y.setObjectName("Y")
        self.H_21 = QtWidgets.QPushButton(parent=Dialog)
        self.H_21.setGeometry(QtCore.QRect(150, 350, 51, 51))
        self.H_21.setText("")
        self.H_21.setObjectName("H_21")
        self.Ti = QtWidgets.QPushButton(parent=Dialog)
        self.Ti.setGeometry(QtCore.QRect(200, 200, 51, 51))
        self.Ti.setObjectName("Ti")
        self.Hf = QtWidgets.QPushButton(parent=Dialog)
        self.Hf.setGeometry(QtCore.QRect(200, 300, 51, 51))
        self.Hf.setObjectName("Hf")
        self.Zr = QtWidgets.QPushButton(parent=Dialog)
        self.Zr.setGeometry(QtCore.QRect(200, 250, 51, 51))
        self.Zr.setObjectName("Zr")
        self.Rf = QtWidgets.QPushButton(parent=Dialog)
        self.Rf.setGeometry(QtCore.QRect(200, 350, 51, 51))
        self.Rf.setObjectName("Rf")
        self.V = QtWidgets.QPushButton(parent=Dialog)
        self.V.setGeometry(QtCore.QRect(250, 200, 51, 51))
        self.V.setObjectName("V")
        self.Ta = QtWidgets.QPushButton(parent=Dialog)
        self.Ta.setGeometry(QtCore.QRect(250, 300, 51, 51))
        self.Ta.setObjectName("Ta")
        self.Nb = QtWidgets.QPushButton(parent=Dialog)
        self.Nb.setGeometry(QtCore.QRect(250, 250, 51, 51))
        self.Nb.setObjectName("Nb")
        self.Db = QtWidgets.QPushButton(parent=Dialog)
        self.Db.setGeometry(QtCore.QRect(250, 350, 51, 51))
        self.Db.setObjectName("Db")
        self.Cr = QtWidgets.QPushButton(parent=Dialog)
        self.Cr.setGeometry(QtCore.QRect(300, 200, 51, 51))
        self.Cr.setObjectName("Cr")
        self.W = QtWidgets.QPushButton(parent=Dialog)
        self.W.setGeometry(QtCore.QRect(300, 300, 51, 51))
        self.W.setObjectName("W")
        self.Mo = QtWidgets.QPushButton(parent=Dialog)
        self.Mo.setGeometry(QtCore.QRect(300, 250, 51, 51))
        self.Mo.setObjectName("Mo")
        self.Sg = QtWidgets.QPushButton(parent=Dialog)
        self.Sg.setGeometry(QtCore.QRect(300, 350, 51, 51))
        self.Sg.setObjectName("Sg")
        self.Mn = QtWidgets.QPushButton(parent=Dialog)
        self.Mn.setGeometry(QtCore.QRect(350, 200, 51, 51))
        self.Mn.setObjectName("Mn")
        self.Re = QtWidgets.QPushButton(parent=Dialog)
        self.Re.setGeometry(QtCore.QRect(350, 300, 51, 51))
        self.Re.setObjectName("Re")
        self.Tc = QtWidgets.QPushButton(parent=Dialog)
        self.Tc.setGeometry(QtCore.QRect(350, 250, 51, 51))
        self.Tc.setObjectName("Tc")
        self.Bh = QtWidgets.QPushButton(parent=Dialog)
        self.Bh.setGeometry(QtCore.QRect(350, 350, 51, 51))
        self.Bh.setObjectName("Bh")
        self.Fe = QtWidgets.QPushButton(parent=Dialog)
        self.Fe.setGeometry(QtCore.QRect(400, 200, 51, 51))
        self.Fe.setObjectName("Fe")
        self.Os = QtWidgets.QPushButton(parent=Dialog)
        self.Os.setGeometry(QtCore.QRect(400, 300, 51, 51))
        self.Os.setObjectName("Os")
        self.Ru = QtWidgets.QPushButton(parent=Dialog)
        self.Ru.setGeometry(QtCore.QRect(400, 250, 51, 51))
        self.Ru.setObjectName("Ru")
        self.Hs = QtWidgets.QPushButton(parent=Dialog)
        self.Hs.setGeometry(QtCore.QRect(400, 350, 51, 51))
        self.Hs.setObjectName("Hs")
        self.Co = QtWidgets.QPushButton(parent=Dialog)
        self.Co.setGeometry(QtCore.QRect(450, 200, 51, 51))
        self.Co.setObjectName("Co")
        self.Ir = QtWidgets.QPushButton(parent=Dialog)
        self.Ir.setGeometry(QtCore.QRect(450, 300, 51, 51))
        self.Ir.setObjectName("Ir")
        self.Rh = QtWidgets.QPushButton(parent=Dialog)
        self.Rh.setGeometry(QtCore.QRect(450, 250, 51, 51))
        self.Rh.setObjectName("Rh")
        self.Mt = QtWidgets.QPushButton(parent=Dialog)
        self.Mt.setGeometry(QtCore.QRect(450, 350, 51, 51))
        self.Mt.setObjectName("Mt")
        self.Ni = QtWidgets.QPushButton(parent=Dialog)
        self.Ni.setGeometry(QtCore.QRect(500, 200, 51, 51))
        self.Ni.setObjectName("Ni")
        self.Pt = QtWidgets.QPushButton(parent=Dialog)
        self.Pt.setGeometry(QtCore.QRect(500, 300, 51, 51))
        self.Pt.setObjectName("Pt")
        self.Pd = QtWidgets.QPushButton(parent=Dialog)
        self.Pd.setGeometry(QtCore.QRect(500, 250, 51, 51))
        self.Pd.setObjectName("Pd")
        self.Ds = QtWidgets.QPushButton(parent=Dialog)
        self.Ds.setGeometry(QtCore.QRect(500, 350, 51, 51))
        self.Ds.setObjectName("Ds")
        self.Cu = QtWidgets.QPushButton(parent=Dialog)
        self.Cu.setGeometry(QtCore.QRect(550, 200, 51, 51))
        self.Cu.setObjectName("Cu")
        self.Au = QtWidgets.QPushButton(parent=Dialog)
        self.Au.setGeometry(QtCore.QRect(550, 300, 51, 51))
        self.Au.setObjectName("Au")
        self.Ag = QtWidgets.QPushButton(parent=Dialog)
        self.Ag.setGeometry(QtCore.QRect(550, 250, 51, 51))
        self.Ag.setObjectName("Ag")
        self.Rg = QtWidgets.QPushButton(parent=Dialog)
        self.Rg.setGeometry(QtCore.QRect(550, 350, 51, 51))
        self.Rg.setObjectName("Rg")
        self.Zn = QtWidgets.QPushButton(parent=Dialog)
        self.Zn.setGeometry(QtCore.QRect(600, 200, 51, 51))
        self.Zn.setObjectName("Zn")
        self.Hg = QtWidgets.QPushButton(parent=Dialog)
        self.Hg.setGeometry(QtCore.QRect(600, 300, 51, 51))
        self.Hg.setObjectName("Hg")
        self.Cd = QtWidgets.QPushButton(parent=Dialog)
        self.Cd.setGeometry(QtCore.QRect(600, 250, 51, 51))
        self.Cd.setObjectName("Cd")
        self.Cn = QtWidgets.QPushButton(parent=Dialog)
        self.Cn.setGeometry(QtCore.QRect(600, 350, 51, 51))
        self.Cn.setObjectName("Cn")
        self.Ga = QtWidgets.QPushButton(parent=Dialog)
        self.Ga.setGeometry(QtCore.QRect(650, 200, 51, 51))
        self.Ga.setObjectName("Ga")
        self.Al = QtWidgets.QPushButton(parent=Dialog)
        self.Al.setGeometry(QtCore.QRect(650, 150, 51, 51))
        self.Al.setObjectName("Al")
        self.Tl = QtWidgets.QPushButton(parent=Dialog)
        self.Tl.setGeometry(QtCore.QRect(650, 300, 51, 51))
        self.Tl.setObjectName("Tl")
        self.In = QtWidgets.QPushButton(parent=Dialog)
        self.In.setGeometry(QtCore.QRect(650, 250, 51, 51))
        self.In.setObjectName("In")
        self.Nh = QtWidgets.QPushButton(parent=Dialog)
        self.Nh.setGeometry(QtCore.QRect(650, 350, 51, 51))
        self.Nh.setObjectName("Nh")
        self.B = QtWidgets.QPushButton(parent=Dialog)
        self.B.setGeometry(QtCore.QRect(650, 100, 51, 51))
        self.B.setObjectName("B")
        self.Ge = QtWidgets.QPushButton(parent=Dialog)
        self.Ge.setGeometry(QtCore.QRect(700, 200, 51, 51))
        self.Ge.setObjectName("Ge")
        self.Si = QtWidgets.QPushButton(parent=Dialog)
        self.Si.setGeometry(QtCore.QRect(700, 150, 51, 51))
        self.Si.setObjectName("Si")
        self.Pb = QtWidgets.QPushButton(parent=Dialog)
        self.Pb.setGeometry(QtCore.QRect(700, 300, 51, 51))
        self.Pb.setObjectName("Pb")
        self.Sn = QtWidgets.QPushButton(parent=Dialog)
        self.Sn.setGeometry(QtCore.QRect(700, 250, 51, 51))
        self.Sn.setObjectName("Sn")
        self.Fl = QtWidgets.QPushButton(parent=Dialog)
        self.Fl.setGeometry(QtCore.QRect(700, 350, 51, 51))
        self.Fl.setObjectName("Fl")
        self.C = QtWidgets.QPushButton(parent=Dialog)
        self.C.setGeometry(QtCore.QRect(700, 100, 51, 51))
        self.C.setObjectName("C")
        self.As = QtWidgets.QPushButton(parent=Dialog)
        self.As.setGeometry(QtCore.QRect(750, 200, 51, 51))
        self.As.setObjectName("As")
        self.P = QtWidgets.QPushButton(parent=Dialog)
        self.P.setGeometry(QtCore.QRect(750, 150, 51, 51))
        self.P.setObjectName("P")
        self.Bi = QtWidgets.QPushButton(parent=Dialog)
        self.Bi.setGeometry(QtCore.QRect(750, 300, 51, 51))
        self.Bi.setObjectName("Bi")
        self.Sb = QtWidgets.QPushButton(parent=Dialog)
        self.Sb.setGeometry(QtCore.QRect(750, 250, 51, 51))
        self.Sb.setObjectName("Sb")
        self.Mc = QtWidgets.QPushButton(parent=Dialog)
        self.Mc.setGeometry(QtCore.QRect(750, 350, 51, 51))
        self.Mc.setObjectName("Mc")
        self.N = QtWidgets.QPushButton(parent=Dialog)
        self.N.setGeometry(QtCore.QRect(750, 100, 51, 51))
        self.N.setObjectName("N")
        self.Se = QtWidgets.QPushButton(parent=Dialog)
        self.Se.setGeometry(QtCore.QRect(800, 200, 51, 51))
        self.Se.setObjectName("Se")
        self.S = QtWidgets.QPushButton(parent=Dialog)
        self.S.setGeometry(QtCore.QRect(800, 150, 51, 51))
        self.S.setObjectName("S")
        self.Po = QtWidgets.QPushButton(parent=Dialog)
        self.Po.setGeometry(QtCore.QRect(800, 300, 51, 51))
        self.Po.setObjectName("Po")
        self.Te = QtWidgets.QPushButton(parent=Dialog)
        self.Te.setGeometry(QtCore.QRect(800, 250, 51, 51))
        self.Te.setObjectName("Te")
        self.Lv = QtWidgets.QPushButton(parent=Dialog)
        self.Lv.setGeometry(QtCore.QRect(800, 350, 51, 51))
        self.Lv.setObjectName("Lv")
        self.o = QtWidgets.QPushButton(parent=Dialog)
        self.o.setGeometry(QtCore.QRect(800, 100, 51, 51))
        self.o.setObjectName("o")
        self.Br = QtWidgets.QPushButton(parent=Dialog)
        self.Br.setGeometry(QtCore.QRect(850, 200, 51, 51))
        self.Br.setObjectName("Br")
        self.Cl = QtWidgets.QPushButton(parent=Dialog)
        self.Cl.setGeometry(QtCore.QRect(850, 150, 51, 51))
        self.Cl.setObjectName("Cl")
        self.At = QtWidgets.QPushButton(parent=Dialog)
        self.At.setGeometry(QtCore.QRect(850, 300, 51, 51))
        self.At.setObjectName("At")
        self.I = QtWidgets.QPushButton(parent=Dialog)
        self.I.setGeometry(QtCore.QRect(850, 250, 51, 51))
        self.I.setObjectName("I")
        self.Ts = QtWidgets.QPushButton(parent=Dialog)
        self.Ts.setGeometry(QtCore.QRect(850, 350, 51, 51))
        self.Ts.setObjectName("Ts")
        self.F = QtWidgets.QPushButton(parent=Dialog)
        self.F.setGeometry(QtCore.QRect(850, 100, 51, 51))
        self.F.setObjectName("F")
        self.Kr = QtWidgets.QPushButton(parent=Dialog)
        self.Kr.setGeometry(QtCore.QRect(900, 200, 51, 51))
        self.Kr.setObjectName("Kr")
        self.Ar = QtWidgets.QPushButton(parent=Dialog)
        self.Ar.setGeometry(QtCore.QRect(900, 150, 51, 51))
        self.Ar.setObjectName("Ar")
        self.Rn = QtWidgets.QPushButton(parent=Dialog)
        self.Rn.setGeometry(QtCore.QRect(900, 300, 51, 51))
        self.Rn.setObjectName("Rn")
        self.He = QtWidgets.QPushButton(parent=Dialog)
        self.He.setGeometry(QtCore.QRect(900, 50, 51, 51))
        self.He.setObjectName("He")
        self.Xe = QtWidgets.QPushButton(parent=Dialog)
        self.Xe.setGeometry(QtCore.QRect(900, 250, 51, 51))
        self.Xe.setObjectName("Xe")
        self.Og = QtWidgets.QPushButton(parent=Dialog)
        self.Og.setGeometry(QtCore.QRect(900, 350, 51, 51))
        self.Og.setObjectName("Og")
        self.Ne = QtWidgets.QPushButton(parent=Dialog)
        self.Ne.setGeometry(QtCore.QRect(900, 100, 51, 51))
        self.Ne.setObjectName("Ne")
        self.H_130 = QtWidgets.QPushButton(parent=Dialog)
        self.H_130.setGeometry(QtCore.QRect(700, 450, 51, 51))
        self.H_130.setObjectName("H_130")
        self.H_131 = QtWidgets.QPushButton(parent=Dialog)
        self.H_131.setGeometry(QtCore.QRect(900, 450, 51, 51))
        self.H_131.setObjectName("H_131")
        self.H_45 = QtWidgets.QPushButton(parent=Dialog)
        self.H_45.setGeometry(QtCore.QRect(300, 450, 51, 51))
        self.H_45.setObjectName("H_45")
        self.H_73 = QtWidgets.QPushButton(parent=Dialog)
        self.H_73.setGeometry(QtCore.QRect(500, 450, 51, 51))
        self.H_73.setObjectName("H_73")
        self.H_80 = QtWidgets.QPushButton(parent=Dialog)
        self.H_80.setGeometry(QtCore.QRect(550, 450, 51, 51))
        self.H_80.setObjectName("H_80")
        self.H_89 = QtWidgets.QPushButton(parent=Dialog)
        self.H_89.setGeometry(QtCore.QRect(600, 450, 51, 51))
        self.H_89.setObjectName("H_89")
        self.H_38 = QtWidgets.QPushButton(parent=Dialog)
        self.H_38.setGeometry(QtCore.QRect(250, 450, 51, 51))
        self.H_38.setObjectName("H_38")
        self.H_132 = QtWidgets.QPushButton(parent=Dialog)
        self.H_132.setGeometry(QtCore.QRect(850, 450, 51, 51))
        self.H_132.setObjectName("H_132")
        self.H_59 = QtWidgets.QPushButton(parent=Dialog)
        self.H_59.setGeometry(QtCore.QRect(400, 450, 51, 51))
        self.H_59.setObjectName("H_59")
        self.H_133 = QtWidgets.QPushButton(parent=Dialog)
        self.H_133.setGeometry(QtCore.QRect(800, 450, 51, 51))
        self.H_133.setObjectName("H_133")
        self.H_134 = QtWidgets.QPushButton(parent=Dialog)
        self.H_134.setGeometry(QtCore.QRect(750, 450, 51, 51))
        self.H_134.setObjectName("H_134")
        self.H_31 = QtWidgets.QPushButton(parent=Dialog)
        self.H_31.setGeometry(QtCore.QRect(200, 450, 51, 51))
        self.H_31.setObjectName("H_31")
        self.H_135 = QtWidgets.QPushButton(parent=Dialog)
        self.H_135.setGeometry(QtCore.QRect(650, 450, 51, 51))
        self.H_135.setObjectName("H_135")
        self.H_52 = QtWidgets.QPushButton(parent=Dialog)
        self.H_52.setGeometry(QtCore.QRect(350, 450, 51, 51))
        self.H_52.setObjectName("H_52")
        self.H_66 = QtWidgets.QPushButton(parent=Dialog)
        self.H_66.setGeometry(QtCore.QRect(450, 450, 51, 51))
        self.H_66.setObjectName("H_66")
        self.H_103 = QtWidgets.QPushButton(parent=Dialog)
        self.H_103.setGeometry(QtCore.QRect(700, 500, 51, 51))
        self.H_103.setObjectName("H_103")
        self.H_128 = QtWidgets.QPushButton(parent=Dialog)
        self.H_128.setGeometry(QtCore.QRect(900, 500, 51, 51))
        self.H_128.setObjectName("H_128")
        self.H_43 = QtWidgets.QPushButton(parent=Dialog)
        self.H_43.setGeometry(QtCore.QRect(300, 500, 51, 51))
        self.H_43.setObjectName("H_43")
        self.H_71 = QtWidgets.QPushButton(parent=Dialog)
        self.H_71.setGeometry(QtCore.QRect(500, 500, 51, 51))
        self.H_71.setObjectName("H_71")
        self.H_78 = QtWidgets.QPushButton(parent=Dialog)
        self.H_78.setGeometry(QtCore.QRect(550, 500, 51, 51))
        self.H_78.setObjectName("H_78")
        self.H_85 = QtWidgets.QPushButton(parent=Dialog)
        self.H_85.setGeometry(QtCore.QRect(600, 500, 51, 51))
        self.H_85.setObjectName("H_85")
        self.H_36 = QtWidgets.QPushButton(parent=Dialog)
        self.H_36.setGeometry(QtCore.QRect(250, 500, 51, 51))
        self.H_36.setObjectName("H_36")
        self.H_129 = QtWidgets.QPushButton(parent=Dialog)
        self.H_129.setGeometry(QtCore.QRect(850, 500, 51, 51))
        self.H_129.setObjectName("H_129")
        self.H_57 = QtWidgets.QPushButton(parent=Dialog)
        self.H_57.setGeometry(QtCore.QRect(400, 500, 51, 51))
        self.H_57.setObjectName("H_57")
        self.H_117 = QtWidgets.QPushButton(parent=Dialog)
        self.H_117.setGeometry(QtCore.QRect(800, 500, 51, 51))
        self.H_117.setObjectName("H_117")
        self.H_110 = QtWidgets.QPushButton(parent=Dialog)
        self.H_110.setGeometry(QtCore.QRect(750, 500, 51, 51))
        self.H_110.setObjectName("H_110")
        self.H_29 = QtWidgets.QPushButton(parent=Dialog)
        self.H_29.setGeometry(QtCore.QRect(200, 500, 51, 51))
        self.H_29.setObjectName("H_29")
        self.H_96 = QtWidgets.QPushButton(parent=Dialog)
        self.H_96.setGeometry(QtCore.QRect(650, 500, 51, 51))
        self.H_96.setObjectName("H_96")
        self.H_50 = QtWidgets.QPushButton(parent=Dialog)
        self.H_50.setGeometry(QtCore.QRect(350, 500, 51, 51))
        self.H_50.setObjectName("H_50")
        self.H_64 = QtWidgets.QPushButton(parent=Dialog)
        self.H_64.setGeometry(QtCore.QRect(450, 500, 51, 51))
        self.H_64.setObjectName("H_64")
        self.text = QtWidgets.QLabel(parent=Dialog)
        self.text.setGeometry(QtCore.QRect(50, 0, 51, 51))
        self.text.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text.setScaledContents(False)
        self.text.setWordWrap(False)
        self.text.setObjectName("text")
        self.text_2 = QtWidgets.QLabel(parent=Dialog)
        self.text_2.setGeometry(QtCore.QRect(100, 0, 51, 51))
        self.text_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_2.setScaledContents(False)
        self.text_2.setWordWrap(False)
        self.text_2.setObjectName("text_2")
        self.text_3 = QtWidgets.QLabel(parent=Dialog)
        self.text_3.setGeometry(QtCore.QRect(150, 0, 51, 51))
        self.text_3.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_3.setScaledContents(False)
        self.text_3.setWordWrap(False)
        self.text_3.setObjectName("text_3")
        self.text_4 = QtWidgets.QLabel(parent=Dialog)
        self.text_4.setGeometry(QtCore.QRect(200, 0, 51, 51))
        self.text_4.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_4.setScaledContents(False)
        self.text_4.setWordWrap(False)
        self.text_4.setObjectName("text_4")
        self.text_5 = QtWidgets.QLabel(parent=Dialog)
        self.text_5.setGeometry(QtCore.QRect(250, 0, 51, 51))
        self.text_5.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_5.setScaledContents(False)
        self.text_5.setWordWrap(False)
        self.text_5.setObjectName("text_5")
        self.text_6 = QtWidgets.QLabel(parent=Dialog)
        self.text_6.setGeometry(QtCore.QRect(300, 0, 51, 51))
        self.text_6.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_6.setScaledContents(False)
        self.text_6.setWordWrap(False)
        self.text_6.setObjectName("text_6")
        self.text_7 = QtWidgets.QLabel(parent=Dialog)
        self.text_7.setGeometry(QtCore.QRect(350, 0, 51, 51))
        self.text_7.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_7.setScaledContents(False)
        self.text_7.setWordWrap(False)
        self.text_7.setObjectName("text_7")
        self.text_8 = QtWidgets.QLabel(parent=Dialog)
        self.text_8.setGeometry(QtCore.QRect(400, 0, 51, 51))
        self.text_8.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_8.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_8.setScaledContents(False)
        self.text_8.setWordWrap(False)
        self.text_8.setObjectName("text_8")
        self.text_9 = QtWidgets.QLabel(parent=Dialog)
        self.text_9.setGeometry(QtCore.QRect(450, 0, 51, 51))
        self.text_9.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_9.setScaledContents(False)
        self.text_9.setWordWrap(False)
        self.text_9.setObjectName("text_9")
        self.text_10 = QtWidgets.QLabel(parent=Dialog)
        self.text_10.setGeometry(QtCore.QRect(500, 0, 51, 51))
        self.text_10.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_10.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_10.setScaledContents(False)
        self.text_10.setWordWrap(False)
        self.text_10.setObjectName("text_10")
        self.text_11 = QtWidgets.QLabel(parent=Dialog)
        self.text_11.setGeometry(QtCore.QRect(550, 0, 51, 51))
        self.text_11.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_11.setScaledContents(False)
        self.text_11.setWordWrap(False)
        self.text_11.setObjectName("text_11")
        self.text_12 = QtWidgets.QLabel(parent=Dialog)
        self.text_12.setGeometry(QtCore.QRect(600, 0, 51, 51))
        self.text_12.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_12.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_12.setScaledContents(False)
        self.text_12.setWordWrap(False)
        self.text_12.setObjectName("text_12")
        self.text_13 = QtWidgets.QLabel(parent=Dialog)
        self.text_13.setGeometry(QtCore.QRect(650, 0, 51, 51))
        self.text_13.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_13.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_13.setScaledContents(False)
        self.text_13.setWordWrap(False)
        self.text_13.setObjectName("text_13")
        self.text_14 = QtWidgets.QLabel(parent=Dialog)
        self.text_14.setGeometry(QtCore.QRect(700, 0, 51, 51))
        self.text_14.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_14.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_14.setScaledContents(False)
        self.text_14.setWordWrap(False)
        self.text_14.setObjectName("text_14")
        self.text_15 = QtWidgets.QLabel(parent=Dialog)
        self.text_15.setGeometry(QtCore.QRect(750, 0, 51, 51))
        self.text_15.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_15.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_15.setScaledContents(False)
        self.text_15.setWordWrap(False)
        self.text_15.setObjectName("text_15")
        self.text_16 = QtWidgets.QLabel(parent=Dialog)
        self.text_16.setGeometry(QtCore.QRect(800, 0, 51, 51))
        self.text_16.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_16.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_16.setScaledContents(False)
        self.text_16.setWordWrap(False)
        self.text_16.setObjectName("text_16")
        self.text_17 = QtWidgets.QLabel(parent=Dialog)
        self.text_17.setGeometry(QtCore.QRect(850, 0, 51, 51))
        self.text_17.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_17.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_17.setScaledContents(False)
        self.text_17.setWordWrap(False)
        self.text_17.setObjectName("text_17")
        self.text_18 = QtWidgets.QLabel(parent=Dialog)
        self.text_18.setGeometry(QtCore.QRect(900, 0, 51, 51))
        self.text_18.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_18.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_18.setScaledContents(False)
        self.text_18.setWordWrap(False)
        self.text_18.setObjectName("text_18")
        self.text_19 = QtWidgets.QLabel(parent=Dialog)
        self.text_19.setGeometry(QtCore.QRect(0, 50, 51, 51))
        self.text_19.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_19.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_19.setScaledContents(False)
        self.text_19.setWordWrap(False)
        self.text_19.setObjectName("text_19")
        self.text_20 = QtWidgets.QLabel(parent=Dialog)
        self.text_20.setGeometry(QtCore.QRect(0, 100, 51, 51))
        self.text_20.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_20.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_20.setScaledContents(False)
        self.text_20.setWordWrap(False)
        self.text_20.setObjectName("text_20")
        self.text_21 = QtWidgets.QLabel(parent=Dialog)
        self.text_21.setGeometry(QtCore.QRect(0, 150, 51, 51))
        self.text_21.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_21.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_21.setScaledContents(False)
        self.text_21.setWordWrap(False)
        self.text_21.setObjectName("text_21")
        self.text_22 = QtWidgets.QLabel(parent=Dialog)
        self.text_22.setGeometry(QtCore.QRect(0, 200, 51, 51))
        self.text_22.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_22.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_22.setScaledContents(False)
        self.text_22.setWordWrap(False)
        self.text_22.setObjectName("text_22")
        self.text_23 = QtWidgets.QLabel(parent=Dialog)
        self.text_23.setGeometry(QtCore.QRect(0, 250, 51, 51))
        self.text_23.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_23.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_23.setScaledContents(False)
        self.text_23.setWordWrap(False)
        self.text_23.setObjectName("text_23")
        self.text_24 = QtWidgets.QLabel(parent=Dialog)
        self.text_24.setGeometry(QtCore.QRect(0, 300, 51, 51))
        self.text_24.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_24.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_24.setScaledContents(False)
        self.text_24.setWordWrap(False)
        self.text_24.setObjectName("text_24")
        self.text_25 = QtWidgets.QLabel(parent=Dialog)
        self.text_25.setGeometry(QtCore.QRect(0, 350, 51, 51))
        self.text_25.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.text_25.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.text_25.setScaledContents(False)
        self.text_25.setWordWrap(False)
        self.text_25.setObjectName("text_25")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(153, 100, 490, 101))
        self.label.setObjectName("label")

        self.H.clicked.connect(self.h)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def h(self):
        with open('bd.txt', 'r') as f2:
            bd = f2.read().split(',')
        self.label.setText(self.pon('H', bd))
        print(self.H.text())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.H.setText(_translate("Dialog", "H"))
        self.Li.setText(_translate("Dialog", "Li"))
        self.Na.setText(_translate("Dialog", "Na"))
        self.K.setText(_translate("Dialog", "K"))
        self.Rb.setText(_translate("Dialog", "Rb"))
        self.Cs.setText(_translate("Dialog", "Cs"))
        self.Fr.setText(_translate("Dialog", "Fr"))
        self.Mg.setText(_translate("Dialog", "Mg"))
        self.Sr.setText(_translate("Dialog", "Sr"))
        self.Ra.setText(_translate("Dialog", "Ra"))
        self.Ba.setText(_translate("Dialog", "Ba"))
        self.Ca.setText(_translate("Dialog", "Ca"))
        self.Be.setText(_translate("Dialog", "Be"))
        self.Sc.setText(_translate("Dialog", "Sc"))
        self.Y.setText(_translate("Dialog", "Y"))
        self.Ti.setText(_translate("Dialog", "Ti"))
        self.Hf.setText(_translate("Dialog", "Hf"))
        self.Zr.setText(_translate("Dialog", "Zr"))
        self.Rf.setText(_translate("Dialog", "Rf"))
        self.V.setText(_translate("Dialog", "V"))
        self.Ta.setText(_translate("Dialog", "Ta"))
        self.Nb.setText(_translate("Dialog", "Nb"))
        self.Db.setText(_translate("Dialog", "Db"))
        self.Cr.setText(_translate("Dialog", "Cr"))
        self.W.setText(_translate("Dialog", "W"))
        self.Mo.setText(_translate("Dialog", "Mo"))
        self.Sg.setText(_translate("Dialog", "Sg"))
        self.Mn.setText(_translate("Dialog", "Mn"))
        self.Re.setText(_translate("Dialog", "Re"))
        self.Tc.setText(_translate("Dialog", "Tc"))
        self.Bh.setText(_translate("Dialog", "Bh"))
        self.Fe.setText(_translate("Dialog", "Fe"))
        self.Os.setText(_translate("Dialog", "Os"))
        self.Ru.setText(_translate("Dialog", "Ru"))
        self.Hs.setText(_translate("Dialog", "Hs"))
        self.Co.setText(_translate("Dialog", "Co"))
        self.Ir.setText(_translate("Dialog", "Ir"))
        self.Rh.setText(_translate("Dialog", "Rh"))
        self.Mt.setText(_translate("Dialog", "Mt"))
        self.Ni.setText(_translate("Dialog", "Ni"))
        self.Pt.setText(_translate("Dialog", "Pt"))
        self.Pd.setText(_translate("Dialog", "Pd"))
        self.Ds.setText(_translate("Dialog", "Ds"))
        self.Cu.setText(_translate("Dialog", "Cu"))
        self.Au.setText(_translate("Dialog", "Au"))
        self.Ag.setText(_translate("Dialog", "Ag"))
        self.Rg.setText(_translate("Dialog", "Rg"))
        self.Zn.setText(_translate("Dialog", "Zn"))
        self.Hg.setText(_translate("Dialog", "Hg"))
        self.Cd.setText(_translate("Dialog", "Cd"))
        self.Cn.setText(_translate("Dialog", "Cn"))
        self.Ga.setText(_translate("Dialog", "Ga"))
        self.Al.setText(_translate("Dialog", "Al"))
        self.Ti_2.setText(_translate("Dialog", "Ti"))
        self.In.setText(_translate("Dialog", "In"))
        self.Nh.setText(_translate("Dialog", "Nh"))
        self.B.setText(_translate("Dialog", "B"))
        self.Ge.setText(_translate("Dialog", "Ge"))
        self.Si.setText(_translate("Dialog", "Si"))
        self.Pb.setText(_translate("Dialog", "Pb"))
        self.Sn.setText(_translate("Dialog", "Sn"))
        self.Fl.setText(_translate("Dialog", "Fl"))
        self.C.setText(_translate("Dialog", "C"))
        self.As.setText(_translate("Dialog", "As"))
        self.P.setText(_translate("Dialog", "P"))
        self.Bi.setText(_translate("Dialog", "Bi"))
        self.Sb.setText(_translate("Dialog", "Sb"))
        self.Mc.setText(_translate("Dialog", "Mc"))
        self.N.setText(_translate("Dialog", "N"))
        self.Se.setText(_translate("Dialog", "Se"))
        self.S.setText(_translate("Dialog", "S"))
        self.Po.setText(_translate("Dialog", "Po"))
        self.Te.setText(_translate("Dialog", "Te"))
        self.Lv.setText(_translate("Dialog", "Lv"))
        self.o.setText(_translate("Dialog", "O"))
        self.Br.setText(_translate("Dialog", "Br"))
        self.Cl.setText(_translate("Dialog", "Cl"))
        self.At.setText(_translate("Dialog", "At"))
        self.I.setText(_translate("Dialog", "I"))
        self.Ts.setText(_translate("Dialog", "Ts"))
        self.F.setText(_translate("Dialog", "F"))
        self.Kr.setText(_translate("Dialog", "Kr"))
        self.Ar.setText(_translate("Dialog", "Ar"))
        self.Rn.setText(_translate("Dialog", "Rn"))
        self.He.setText(_translate("Dialog", "He"))
        self.Xe.setText(_translate("Dialog", "Xe"))
        self.Og.setText(_translate("Dialog", "Og"))
        self.Ne.setText(_translate("Dialog", "Ne"))
        self.H_130.setText(_translate("Dialog", "Ho"))
        self.H_131.setText(_translate("Dialog", "Lu"))
        self.H_45.setText(_translate("Dialog", "Pr"))
        self.H_73.setText(_translate("Dialog", "Eu"))
        self.H_80.setText(_translate("Dialog", "Gd"))
        self.H_89.setText(_translate("Dialog", "Tb"))
        self.H_38.setText(_translate("Dialog", "Ce"))
        self.H_132.setText(_translate("Dialog", "Yb"))
        self.H_59.setText(_translate("Dialog", "Pm"))
        self.H_133.setText(_translate("Dialog", "Tm"))
        self.H_134.setText(_translate("Dialog", "Er"))
        self.H_31.setText(_translate("Dialog", "La"))
        self.H_135.setText(_translate("Dialog", "Dy"))
        self.H_52.setText(_translate("Dialog", "Nd"))
        self.H_66.setText(_translate("Dialog", "Sm"))
        self.H_103.setText(_translate("Dialog", "Es"))
        self.H_128.setText(_translate("Dialog", "Lr"))
        self.H_43.setText(_translate("Dialog", "Pa"))
        self.H_71.setText(_translate("Dialog", "Am"))
        self.H_78.setText(_translate("Dialog", "Cm"))
        self.H_85.setText(_translate("Dialog", "Bk"))
        self.H_36.setText(_translate("Dialog", "Th"))
        self.H_129.setText(_translate("Dialog", "No"))
        self.H_57.setText(_translate("Dialog", "Np"))
        self.H_117.setText(_translate("Dialog", "Md"))
        self.H_110.setText(_translate("Dialog", "Fm"))
        self.H_29.setText(_translate("Dialog", "Ac"))
        self.H_96.setText(_translate("Dialog", "Cf"))
        self.H_50.setText(_translate("Dialog", "U"))
        self.H_64.setText(_translate("Dialog", "Pu"))
        self.text.setText(_translate("Dialog", "1"))
        self.text_2.setText(_translate("Dialog", "2"))
        self.text_3.setText(_translate("Dialog", "3"))
        self.text_4.setText(_translate("Dialog", "4"))
        self.text_5.setText(_translate("Dialog", "5"))
        self.text_6.setText(_translate("Dialog", "6"))
        self.text_7.setText(_translate("Dialog", "7"))
        self.text_8.setText(_translate("Dialog", "8"))
        self.text_9.setText(_translate("Dialog", "9"))
        self.text_10.setText(_translate("Dialog", "10"))
        self.text_11.setText(_translate("Dialog", "11"))
        self.text_12.setText(_translate("Dialog", "12"))
        self.text_13.setText(_translate("Dialog", "13"))
        self.text_14.setText(_translate("Dialog", "14"))
        self.text_15.setText(_translate("Dialog", "15"))
        self.text_16.setText(_translate("Dialog", "16"))
        self.text_17.setText(_translate("Dialog", "17"))
        self.text_18.setText(_translate("Dialog", "18"))
        self.text_19.setText(_translate("Dialog", "1"))
        self.text_20.setText(_translate("Dialog", "2"))
        self.text_21.setText(_translate("Dialog", "3"))
        self.text_22.setText(_translate("Dialog", "4"))
        self.text_23.setText(_translate("Dialog", "5"))
        self.text_24.setText(_translate("Dialog", "6"))
        self.text_25.setText(_translate("Dialog", "7"))

    def pon(self, k: str, bd: list):
        for i in range(len(bd)):
            if bd[i] == k:
                return f"{bd[i - 1]},{bd[i]},{bd[i + 1]},{bd[i + 2]},{bd[i + 3]},{bd[i + 4]}"

    def settext(self):
        with open('bd.txt', 'r') as f2:
            bd = f2.read().split(',')

        def pon(k):
            for i in range(len(bd)):
                if bd[i] == k:
                    self.label.setText ("Dialog",bd[i - 1], bd[i], bd[i + 1], bd[i + 2], bd[i + 3], bd[i + 4])